import type { Metadata } from "next";
import { Cedarville_Cursive } from "next/font/google";
import "./globals.css";

/////////  for using fonts whith tailwind
export const cedar = Cedarville_Cursive({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-cedar",
});

import Header from "@/components/Header/Index";
import { AppWrapper } from "@/contexts/app-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppWrapper>
        <body>
          <Header name={"toto"} />
          {children}
        </body>
      </AppWrapper>
    </html>
  );
}
